name: Deploy Laravel App (Working Fix)

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to Server
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        port: ${{ secrets.SERVER_PORT }}
        script: |
          # Go to your Laravel directory
          cd /home/pragati/htdocs/pragati.coop.np

          # Fix Git security issue
          git config --global --add safe.directory /home/pragati/htdocs/pragati.coop.np

          # Pull latest changes (force overwrite any local changes)
          git reset --hard HEAD
          git pull origin main

          # Install/update composer dependencies
          export COMPOSER_ALLOW_SUPERUSER=1
          composer install --optimize-autoloader --no-dev --no-plugins

          # Clear Laravel caches before permission fix
          php artisan config:clear
          php artisan cache:clear

          # NUCLEAR OPTION - Make everything writable (your working solution)
          sudo chmod -R 777 storage/
          sudo chmod -R 777 bootstrap/
          sudo chmod -R 777 /home/pragati/htdocs/pragati.coop.np/

          # Create all missing directories
          sudo mkdir -p storage/framework/views
          sudo mkdir -p storage/framework/cache
          sudo mkdir -p storage/framework/sessions
          sudo mkdir -p storage/logs
          sudo mkdir -p bootstrap/cache

          # Set ownership to the web server user
          sudo chown -R www-data:www-data /home/pragati/htdocs/pragati.coop.np/

          # Rebuild Laravel caches with correct permissions
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache

          echo "✅ Deployment completed with permission fix!"
