name: Deploy Laravel App

on:
  push:
    branches: [ main ]  # Change to your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to Server
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        port: ${{ secrets.SERVER_PORT }}
        script: |
          cd /var/www/html/your-repo-name
          git pull origin main
          composer install --optimize-autoloader --no-dev
          php artisan config:clear
          php artisan cache:clear
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache
          sudo chown -R www-data:www-data storage bootstrap/cache
          sudo chmod -R 775 storage bootstrap/cache
